# Generated by Django 2.2.4 on 2019-11-21 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leveldefinition',
            name='designations',
        ),
        migrations.RemoveField(
            model_name='leveldefinition',
            name='grades',
        ),
        migrations.CreateModel(
            name='LevelDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Job')),
                ('levelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Leveldefinition')),
            ],
        ),
    ]
