# Generated by Django 2.2.4 on 2019-11-21 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('organisation', '0002_auto_20191121_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leveldesignation',
            name='grades',
        ),
        migrations.AddField(
            model_name='leveldesignation',
            name='designations',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.Job'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LevelGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Job')),
                ('levelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Leveldefinition')),
            ],
        ),
    ]
