# Generated by Django 2.2.4 on 2019-11-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_auto_20191121_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelgrades',
            name='grades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Jobgrade'),
        ),
    ]
