# Generated by Django 2.2.5 on 2019-12-14 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_auto_20191121_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveldesignation',
            name='levelid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leveldesignation', to='organisation.Leveldefinition'),
        ),
        migrations.AlterField(
            model_name='levelgrades',
            name='levelid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levelgrades', to='organisation.Leveldefinition'),
        ),
    ]
