# Generated by Django 2.2.5 on 2019-12-14 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_auto_20191214_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveldesignation',
            name='levelid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Leveldefinition'),
        ),
        migrations.AlterField(
            model_name='levelgrades',
            name='levelid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Leveldefinition'),
        ),
    ]
