# Generated by Django 2.2.4 on 2019-09-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobdescription',
            field=models.CharField(max_length=100),
        ),
    ]
