# Generated by Django 2.2.5 on 2019-11-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_auto_20191114_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='locations',
            new_name='location',
        ),
    ]
