# Generated by Django 2.2.5 on 2019-11-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='title',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
