# Generated by Django 2.2.5 on 2019-09-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_auto_20190924_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcategory', models.CharField(max_length=50)),
            ],
        ),
    ]
