# Generated by Django 2.2.5 on 2019-09-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_jobcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobgrade', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
    ]
