# Generated by Django 2.2.5 on 2019-11-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_emailtemplate_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
