# Generated by Django 2.2.5 on 2019-11-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_auto_20191114_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='area',
        ),
    ]
