# Generated by Django 2.2.5 on 2019-12-23 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_auto_20191127_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiftname', models.CharField(max_length=150)),
                ('shortname', models.CharField(max_length=150)),
                ('shiftdescription', models.CharField(max_length=150)),
                ('flexibleshift', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftTimings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workdays', models.SmallIntegerField(default=0)),
                ('shift_in_time', models.TimeField()),
                ('shift_out_time', models.TimeField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('weekoff', models.SmallIntegerField(default=2)),
                ('shift_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.ShiftDetails')),
            ],
        ),
    ]
