# Generated by Django 2.2.5 on 2019-09-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_salarycomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employmentstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employementstatus', models.CharField(max_length=50)),
            ],
        ),
    ]
