# Generated by Django 2.2.5 on 2019-09-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobgrade',
            name='currency',
        ),
    ]
