# Generated by Django 2.2.5 on 2019-10-16 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
        migrations.RemoveField(
            model_name='job',
            name='updated_at',
        ),
    ]
