# Generated by Django 2.2.5 on 2019-10-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_auto_20191016_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
