# Generated by Django 2.2.5 on 2019-10-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('middle_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('employee_id', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.SmallIntegerField(default=1)),
                ('gender', models.SmallIntegerField(default=1)),
                ('nationality', models.BigIntegerField(default=1)),
                ('nick_name', models.CharField(blank=True, max_length=150)),
                ('aadhar_card_no', models.BigIntegerField()),
                ('joined_date', models.DateField()),
                ('date_of_permanency', models.DateField()),
                ('job_title', models.BigIntegerField(default=1)),
                ('employment_status', models.BigIntegerField(default=1)),
                ('job_category', models.BigIntegerField(default=1)),
                ('work_shifts', models.IntegerField(default=1)),
                ('department', models.BigIntegerField(default=1)),
                ('worklocation', models.BigIntegerField(default=1)),
            ],
        ),
    ]
