# Generated by Django 2.2.5 on 2019-11-20 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('employee_id', models.CharField(max_length=150)),
                ('emailid', models.EmailField(max_length=150)),
                ('mobilenumber', models.CharField(max_length=15)),
                ('gender', models.SmallIntegerField(default=1)),
                ('marital_status', models.SmallIntegerField(default=1)),
                ('nationality', models.SmallIntegerField(default=1)),
                ('aadhar_card_no', models.BigIntegerField()),
                ('joined_date', models.DateField()),
                ('date_of_permanency', models.DateField()),
                ('work_shifts', models.IntegerField(default=1)),
                ('isHOD', models.SmallIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Department')),
                ('employmentLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Leveldefinition')),
                ('employment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Employmentstatus')),
                ('job_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Jobgrade')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Job')),
                ('worklocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Location')),
            ],
        ),
    ]
