# Generated by Django 2.2.5 on 2019-10-18 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Department'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='employment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Employmentstatus'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='job_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Jobcategory'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Job'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='worklocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Location'),
        ),
    ]
