# Generated by Django 2.2.4 on 2019-11-19 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_auto_20191118_1728'),
        ('organisation', '0001_initial'),
        ('pim', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_details',
            name='job_category',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='nick_name',
        ),
        migrations.AddField(
            model_name='personal_details',
            name='emailid',
            field=models.EmailField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_details',
            name='employmentLevel',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='organisation.Leveldefinition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_details',
            name='job_grade',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='masters.Jobgrade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_details',
            name='mobilenumber',
            field=models.CharField(default=2121212, max_length=15),
            preserve_default=False,
        ),
    ]
