# Generated by Django 2.2.5 on 2019-10-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='employee_id',
            field=models.CharField(max_length=150),
        ),
    ]
