# Generated by Django 2.2.4 on 2019-11-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='isHOD',
            field=models.SmallIntegerField(default=0),
        ),
    ]
