# Generated by Django 2.2.4 on 2019-10-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0002_auto_20191011_1144'),
        ('pim', '0002_auto_20191010_1204'),
    ]

    operations = [
    ]
