# Generated by Django 2.2.4 on 2019-11-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0002_auto_20191119_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='isHOD',
            field=models.SmallIntegerField(default=0),
        ),
    ]
