# Generated by Django 2.2.4 on 2019-11-20 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='reportingTo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pim.Personal_details'),
            preserve_default=False,
        ),
    ]
