# Generated by Django 2.2.5 on 2019-10-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0003_auto_20191012_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='date_of_permanency',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='joined_date',
            field=models.DateTimeField(),
        ),
    ]
