# Generated by Django 2.2.5 on 2019-10-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0005_auto_20191012_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='department',
            field=models.CharField(default=1, max_length=150),
        ),
    ]
