# Generated by Django 2.2.5 on 2019-10-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0006_personal_details_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='department',
            field=models.BigIntegerField(default=1),
        ),
    ]
