# Generated by Django 2.2.4 on 2019-11-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0004_personal_details_reportingto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='employmentLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Leveldefinition'),
        ),
    ]
