# Generated by Django 2.2.5 on 2019-10-12 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0007_auto_20191012_0551'),
        ('pim', '0002_auto_20191010_1204'),
    ]

    operations = [
    ]
