# Generated by Django 2.2.5 on 2019-10-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0008_merge_20191012_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='nationality',
            field=models.CharField(max_length=150),
        ),
    ]
