# Generated by Django 2.2.4 on 2019-11-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0008_auto_20191121_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='reportingTo_id',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
