# Generated by Django 2.2.5 on 2019-10-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0009_auto_20191014_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='nationality',
            field=models.SmallIntegerField(default=1),
        ),
    ]
