# Generated by Django 2.2.4 on 2019-11-22 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0009_auto_20191122_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='reportingTo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pim.Personal_details'),
        ),
    ]
