# Generated by Django 2.2.5 on 2019-10-15 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0010_auto_20191014_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Job'),
        ),
    ]
