# Generated by Django 2.2.5 on 2019-10-15 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0011_auto_20191015_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='employment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Employmentstatus'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Location'),
        ),
    ]
