# Generated by Django 2.2.4 on 2019-11-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0011_auto_20191123_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_details',
            old_name='isHOD',
            new_name='DUHead',
        ),
    ]
