# Generated by Django 2.2.4 on 2019-10-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0003_merge_20191011_1252'),
        ('pim', '0012_auto_20191015_1053'),
    ]

    operations = [
    ]
