# Generated by Django 2.2.4 on 2019-11-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0012_auto_20191123_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_details',
            name='reportingTo_id',
        ),
        migrations.AddField(
            model_name='personal_details',
            name='reportingto',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
