# Generated by Django 2.2.4 on 2019-10-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0013_merge_20191016_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='nationality',
            field=models.SmallIntegerField(default=1),
        ),
    ]
