# Generated by Django 2.2.4 on 2019-11-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0013_auto_20191126_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='reportingdepartment',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='reportingtoId',
            field=models.SmallIntegerField(default=1),
        ),
    ]
