# Generated by Django 2.2.5 on 2019-12-23 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0014_auto_20191126_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='work_shifts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.ShiftDetails'),
        ),
    ]
