# Generated by Django 2.2.4 on 2019-10-17 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_auto_20191016_0406'),
        ('pim', '0014_auto_20191017_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='worklocation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.Location'),
        ),
    ]
