# Generated by Django 2.2.4 on 2019-10-17 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0015_personal_details_worklocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='worklocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Location'),
        ),
    ]
