# Generated by Django 2.2.5 on 2020-01-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0015_auto_20191223_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='alternate_emailid',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='alternate_mobileno',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
