# Generated by Django 2.2.4 on 2019-10-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0017_auto_20191017_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='first_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='last_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
