# Generated by Django 2.2.5 on 2019-11-20 07:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leavestructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('leavestructure', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('leavedescription', models.CharField(max_length=100)),
                ('experincefrom', models.IntegerField()),
                ('experienceto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Leavetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavetype', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=3)),
                ('leavedescription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Linktoleavetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfLeaves', models.SmallIntegerField(default=1)),
                ('leave_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.Leavestructure')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.Leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='AssignLeaveStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('updatedDate', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pim.Personal_details')),
                ('leave_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.Leavestructure')),
            ],
        ),
    ]
