# Generated by Django 2.2.5 on 2019-11-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linktoleavetype',
            name='leave_structure',
        ),
    ]
