# Generated by Django 2.2.5 on 2019-11-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holidayname', models.CharField(max_length=50)),
                ('holidayDate', models.DateField()),
            ],
        ),
    ]
