# Generated by Django 2.2.5 on 2019-11-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_remove_linktoleavetype_leave_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linktoleavetype',
            options={},
        ),
        migrations.AddField(
            model_name='linktoleavetype',
            name='leave_structure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leaves.Leavestructure'),
        ),
    ]
