# Generated by Django 2.2.5 on 2019-11-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_holidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='holidayDate',
            field=models.DateField(blank=False),
        ),
    ]
