# Generated by Django 2.2.4 on 2019-11-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_auto_20191120_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='holidayDate',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
