# Generated by Django 2.2.5 on 2019-11-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_auto_20191121_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_list',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
