# Generated by Django 2.2.4 on 2019-11-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_leavedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavedetails',
            name='AppliedDate',
            field=models.DateField(),
        ),
    ]
