# Generated by Django 2.2.4 on 2019-11-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_assignleavestructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='shortname',
            field=models.CharField(default=2, max_length=3),
            preserve_default=False,
        ),
    ]
