# Generated by Django 2.2.4 on 2019-12-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_leavedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavedetails',
            name='NumberOfLeaves',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
    ]
