# Generated by Django 2.2.4 on 2019-11-14 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_leavetype_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavestructure',
            name='shortname',
            field=models.CharField(default=1, max_length=3, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
            preserve_default=False,
        ),
    ]
