# Generated by Django 2.2.5 on 2019-12-23 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_auto_20191214_1513'),
        ('leaves', '0007_auto_20191210_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssigningLevelsToStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavestructureid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.Leavestructure')),
                ('levels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Leveldefinition')),
            ],
        ),
    ]
