# Generated by Django 2.2.4 on 2019-11-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0007_leavestructure_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavestructure',
            name='experienceto',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavestructure',
            name='experincefrom',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
