# Generated by Django 2.2.5 on 2019-12-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0008_assigninglevelstostructure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload_list',
        ),
    ]
