# Generated by Django 2.2.5 on 2020-01-17 12:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20200117_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payscale',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payscale',
            name='experienceto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payscale',
            name='experincefrom',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payscale',
            name='payscalename',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='payscale',
            name='shortname',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
