# Generated by Django 2.2.5 on 2020-01-18 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_auto_20191214_1513'),
        ('payroll', '0004_auto_20200117_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssigningLevelsToPayscale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Leveldefinition')),
                ('payscalenameid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.PayScale')),
            ],
        ),
    ]
