# Generated by Django 2.2.5 on 2020-01-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0015_auto_20191223_1005'),
        ('payroll', '0006_linktocomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignPayscale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('updatedDate', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pim.Personal_details')),
                ('pay_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.PayScale')),
            ],
        ),
    ]
