# Generated by Django 2.2.5 on 2019-12-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiftname', models.CharField(max_length=150)),
                ('shortname', models.CharField(max_length=150)),
                ('shiftdescription', models.CharField(max_length=150)),
                ('flexibleshift', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TardinessDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxallowedlate', models.SmallIntegerField(default=0)),
                ('penalty_late', models.SmallIntegerField(default=3)),
                ('maxallowedearly', models.SmallIntegerField(default=0)),
                ('penalty_early', models.SmallIntegerField(default=3)),
                ('holidaycompensatorytype', models.SmallIntegerField(default=2)),
                ('holidaypaymentqty', models.SmallIntegerField(default=3)),
                ('holidaydaystoexpire', models.SmallIntegerField(default=1)),
                ('weekendcompensatorytype', models.SmallIntegerField(default=2)),
                ('weekendpaymentqty', models.SmallIntegerField(default=3)),
                ('weekenddaystoexpire', models.SmallIntegerField(default=1)),
                ('minimumHoursForOT', models.SmallIntegerField(default=2)),
                ('OTcompensatorytype', models.SmallIntegerField(default=2)),
                ('OTPayment', models.SmallIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftTimings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workdays', models.SmallIntegerField(default=0)),
                ('shift_in_time', models.TimeField()),
                ('shift_out_time', models.TimeField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('weekoff', models.SmallIntegerField(default=2)),
                ('shift_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.ShiftDetails')),
            ],
        ),
    ]
