# Generated by Django 2.2.4 on 2019-11-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TardinessDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxallowedlate', models.SmallIntegerField(default=0)),
                ('penalty_late', models.SmallIntegerField(default=3)),
                ('maxallowedearly', models.SmallIntegerField(default=0)),
                ('penalty_early', models.SmallIntegerField(default=3)),
                ('holidaycompensatorytype', models.SmallIntegerField(default=2)),
                ('holidaypaymentqty', models.SmallIntegerField(default=3)),
                ('weekendcompensatorytype', models.SmallIntegerField(default=2)),
                ('weekendpaymentqty', models.SmallIntegerField(default=3)),
            ],
        ),
    ]
