# Generated by Django 2.2.5 on 2019-12-13 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0014_auto_20191126_1313'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftdetails',
            name='flexibleshift',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shifttimings',
            name='workdays',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tardinessdetails',
            name='OTPayment',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('employee_name', models.CharField(max_length=150)),
                ('employee_shift', models.CharField(max_length=150)),
                ('employee_intime', models.TimeField()),
                ('employee_outime', models.TimeField()),
                ('employee_workduration', models.TimeField()),
                ('employee_OT', models.TimeField()),
                ('employee_totalwork', models.TimeField()),
                ('holiday_status', models.SmallIntegerField(default=2)),
                ('weekend_status', models.SmallIntegerField(default=2)),
                ('attendance_status', models.SmallIntegerField(default=1)),
                ('leave_status', models.SmallIntegerField(default=1)),
                ('compoff_status', models.SmallIntegerField(default=1)),
                ('updated_date_time', models.DateTimeField()),
                ('employee_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pim.Personal_details')),
            ],
        ),
    ]
