# Generated by Django 2.2.4 on 2019-11-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20191127_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='tardinessdetails',
            name='holidaydaystoexpire',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tardinessdetails',
            name='weekenddaystoexpire',
            field=models.SmallIntegerField(default=1),
        ),
    ]
