# Generated by Django 2.2.4 on 2019-12-05 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0014_auto_20191126_1313'),
        ('attendance', '0003_auto_20191129_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=150)),
                ('employee_shift', models.CharField(max_length=150)),
                ('employee_intime', models.TimeField()),
                ('employee_outime', models.TimeField()),
                ('employee_workduration', models.TimeField()),
                ('employee_OT', models.TimeField()),
                ('employee_totalwork', models.TimeField()),
                ('holiday_status', models.SmallIntegerField(default=2)),
                ('weekend_status', models.SmallIntegerField(default=2)),
                ('attendance_status', models.SmallIntegerField(default=1)),
                ('leave_status', models.SmallIntegerField(default=1)),
                ('compoff_status', models.SmallIntegerField(default=1)),
                ('updated_date_time', models.TimeField()),
                ('employee_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pim.Personal_details')),
            ],
        ),
    ]
