# Generated by Django 2.2.4 on 2019-12-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_employeeattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='updated_date_time',
            field=models.DateTimeField(),
        ),
    ]
