# Generated by Django 2.2.4 on 2019-12-05 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20191205_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='attendance_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
